spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
amplia.rabbitmq.exchange=amplia.exchange
amplia.rabbitmq.queue=amplia.queue
amplia.rabbitmq.routingkey=amplia.routingkey
